export const QUERY_USER_INFO = 'QUERY_USER_INFO';

export const COURSE_QUERY_BANNER = 'COURSE_QUERY_BANNER';

export const COURSE_DETAILS = 'COURSE_DETAILS';

export const COURSE_UNPAY = 'COURSE_UNPAY';
